spring:
  datasource:
    url: ${POSTGRESQL.URL_CONNECTION}
    username: ${POSTGRESQL.USERNAME}
    password: ${POSTGRESQL.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect